### ISSUE TITLE
Swift iOS8 Support

### ISSUE THREAD

**Issue by fender** [appbotx/appbotx#10]
Does appbotx support Swift and iOS8?

**Comment by stuartkhall** [comment]
Hi there,

It definitely works with iOS 8, others have reported using it with a bridging header. We haven't officially supported it yet but we are working on it.

Thanks!

**Comment by fender** [comment]
@stuartkhall Thanks for the reply. Is there any online reference to how someone did it? I've copied over the `appbotx-1.0.6` release into the Frameworks folder of my project and in my bridging header..

```
#import <Parse/Parse.h>
#import <ParseCrashReporting/ParseCrashReporting.h>
#import "ABX.h"
```

It seems to be importing the header file but I get an error:

`/Users/jfender/Documents/Workspace/Xcode/Tourney/Frameworks/appbotx-1.0.6/Classes/Classes/ABXApiClient.h:34:59: Expected a type`

Which refers to this line:
`- (NSURLSessionDataTask*)POSTImage:(NSString*)path image:(UIImage*)image complete:(ABXRequestCompletion)complete;`

**Comment by stuartkhall** [comment]
Hi,

Unfortunately I don't, I've reached out to a couple of customers that said they have done this to see if they have any feedback.

Thanks!
Stuart
